Bookify.Web/Controllers/ReportsController.cs
using Bookify.Application.Common.Models;
using ClosedXML.Excel;
using OpenHtmlToPdf;
using ViewToHTML.Services;

namespace Bookify.Web.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly IViewRendererService _viewRendererService;

        public ReportsController(ApplicationDbContext context, IMapper mapper,
            IViewRendererService viewRendererService)
        {
            _context = context;
            _mapper = mapper;
            _viewRendererService = viewRendererService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Doctors(DateTime From, DateTime To, int? pageNumber)
        {
            var rentals = _context.RentalCopies
                .Include(r => r.Rental)
                .ThenInclude(r => r!.Subscriper)
                .Include(r => r.BookCopy)
                .ThenInclude(c => c!.Book)
                .ThenInclude(r => r!.Author)
                .Where(c => c.ReturnDate >= From && c.EndDate <= To);

            DoctorReportViewModel viewModel = new()
            {
                Rentals = PaginatedList<RentalCopy>.Create(rentals, 1, 10),
                PageMode = 1
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Clinics(IList<int> selectedAuthor, IList<int> selectedCategories
            , int? pageNumber)
        {
            var author = _context.Authors.OrderBy(a => a.Name).ToList();
            var categories = _context.Categories.OrderBy(a => a.Name).ToList();

            IQueryable<Book> books = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (selectedAuthor.Any())
                books = books.Where(b => selectedAuthor.Contains(b.AuthorId));

            if (selectedCategories.Any())
                books = books.Where(b => b.Categories.Any(c => selectedCategories.Contains(c.CategoryId)));

            ClinicReportViewModel viewModel = new()
            {
                Authors = _mapper.Map<IEnumerable<SelectListItem>>(author),
                Categories = _mapper.Map<IEnumerable<SelectListItem>>(categories)
            };

            if (pageNumber is not null)
                viewModel.Books = PaginatedList<Book>.Create(books, pageNumber ?? 0, 10);

            return View(viewModel); ;
        }

        [HttpGet]
        public async Task<IActionResult> ExportDatatoExcel(string authors, string categories)
        {

            var selectedAuthor = authors?.Split(",");
            var selectedCategories = categories?.Split(",");

            IQueryable<Book> booksQuerable = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (!string.IsNullOrEmpty(authors))
                booksQuerable = booksQuerable.Where(b => selectedAuthor!.Contains(b.AuthorId.ToString()));

            if (!string.IsNullOrEmpty(categories))
                booksQuerable = booksQuerable.Where(b => b.Categories.Any(c => selectedCategories!.Contains(c.CategoryId.ToString())));

            var books = booksQuerable.ToList();

            using var workbook = new XLWorkbook();

            var sheet = workbook.AddWorksheet("Books");

            var headerCells = new string[] { "Title" , "Author" , "Categories" , "Publisher" ,
                               "Publishing Date", "Hall" , "Is avaliable for Rental" , "Status" };

            sheet.AddHeader(headerCells);

            for (int i = 0; i < books.Count; i++)
            {
                sheet.Cell(i + 2, 1).SetValue(books[i].Title);
                sheet.Cell(i + 2, 2).SetValue(books[i].Author!.Name);
                sheet.Cell(i + 2, 3).SetValue(string.Join(", ", books[i].Categories.Select(c => c.Category!.Name)));
                sheet.Cell(i + 2, 4).SetValue(books[i].Publisher);
                sheet.Cell(i + 2, 5).SetValue(books[i].PublishingDate.ToString("dd-MM-yyyy"));
                sheet.Cell(i + 2, 6).SetValue(books[i].Hall);
                sheet.Cell(i + 2, 7).SetValue(books[i].IsAvailableForRent ? "yes" : "no");
                sheet.Cell(i + 2, 8).SetValue(books[i].IsDeleted ? "deleted" : "available");
            }

            sheet.AddFormate();

            await using var stream = new MemoryStream();

            workbook.SaveAs(stream);

            return File(stream.ToArray(), "application/octet-stream", $"books_{DateTime.Now}.xlsx");

        }

        [HttpGet]
        public async Task<IActionResult> ExportDatatoPDF(string authors, string categories)
        {

            var selectedAuthor = authors?.Split(",");
            var selectedCategories = categories?.Split(",");

            IQueryable<Book> booksQuerable = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (!string.IsNullOrEmpty(authors))
                booksQuerable = booksQuerable.Where(b => selectedAuthor!.Contains(b.AuthorId.ToString()));

            if (!string.IsNullOrEmpty(categories))
                booksQuerable = booksQuerable.Where(b => b.Categories.Any(c => selectedCategories!.Contains(c.CategoryId.ToString())));

            var books = booksQuerable.ToList();

            var tempPath = "~/Views/Reports/ReportPdf.cshtml";

            var html = await _viewRendererService.RenderViewToStringAsync(ControllerContext, tempPath, books);

            var pdf = Pdf.From(html).Content();

            //.Encodwith("Utf-8") => if u have any problem to Arabic
            //.LandScape() => To show data at landscape

            return File(pdf.ToArray(), "application/octet-stream", $"books_{DateTime.Now}.pdf");

        }

        [HttpGet]
        public async Task<IActionResult> ExportDoctortoExcel(DateTime From, DateTime To, int? pageNumber)
        {

            var rentalsQuery = _context.RentalCopies
                .Include(r => r.Rental)
                .ThenInclude(r => r!.Subscriper)
                .Include(r => r.BookCopy)
                .ThenInclude(c => c!.Book)
                .ThenInclude(r => r!.Author)
                .Where(c => c.ReturnDate >= From && c.EndDate <= To);


            var rentals = rentalsQuery.ToList();

            using var workbook = new XLWorkbook();

            var sheet = workbook.AddWorksheet("Rentals");

            var headerCells = new string[] { "Subscriber ID" , "Subscriber Name" , "Subscriber Phone" ,"Author Name", "Book Title" ,
                               "Rental Date", "End Date" , "Return Date" , "Extended On" };

            sheet.AddHeader(headerCells);

            for (int i = 0; i < rentals.Count; i++)
            {
                sheet.Cell(i + 2, 1).SetValue(rentals[i].Rental!.Subscriper!.Id);
                sheet.Cell(i + 2, 2).SetValue(rentals[i].Rental!.Subscriper!.FirstName);
                sheet.Cell(i + 2, 3).SetValue(rentals[i].Rental!.Subscriper!.MobileNumber);
                sheet.Cell(i + 2, 4).SetValue(rentals[i].BookCopy!.Book!.Author!.Name);
                sheet.Cell(i + 2, 5).SetValue(rentals[i].BookCopy!.Book!.Title);
                sheet.Cell(i + 2, 6).SetValue(rentals[i].RentalDate.ToString("dd-MM-yyyy"));
                sheet.Cell(i + 2, 7).SetValue(rentals[i].EndDate.ToString("dd-MM-yyyy"));
                sheet.Cell(i + 2, 8).SetValue(rentals[i].ReturnDate?.ToString("dd-MM-yyyy"));
                sheet.Cell(i + 2, 9).SetValue(rentals[i].ExtendOn?.ToString("dd-MM-yyyy"));
            }

            sheet.AddFormate();

            await using var stream = new MemoryStream();

            workbook.SaveAs(stream);

            return File(stream.ToArray(), "application/octet-stream", $"Rentals_{DateTime.Now}.xlsx");

        }

        [HttpGet]
        public async Task<IActionResult> ExportDoctortoPDF(DateTime From, DateTime To)
        {

            var rentalsQuery = _context.RentalCopies
                .Include(r => r.Rental)
                .ThenInclude(r => r!.Subscriper)
                .Include(r => r.BookCopy)
                .ThenInclude(c => c!.Book)
                .ThenInclude(r => r!.Author)
                .Where(c => c.ReturnDate >= From && c.EndDate <= To);


            var rentals = rentalsQuery.ToList();

            var tempPath = "~/Views/Reports/ReportDoctorPdf.cshtml";

            var html = await _viewRendererService.RenderViewToStringAsync(ControllerContext, tempPath, rentals);

            var pdf = Pdf
                .From(html)
                .Landscape()
                .Content();

            return File(pdf.ToArray(), "application/octet-stream", $"Rentals_{DateTime.Now}.pdf");

        }

        [HttpGet]
        public IActionResult DelayedPatient()
        {
            var rentals = getDelayedRental();

            DoctorReportViewModel viewModel = new()
            {
                Rentals = PaginatedList<RentalCopy>.Create(rentals, 1, 10),
                PageMode = 2
            };

            return View(nameof(Doctors), viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ExportDelayedPatientToExcel(DateTime From, DateTime To, int? pageNumber)
        {
            var rentalsQuery = getDelayedRental();

            var rentals = rentalsQuery.ToList();

            using var workbook = new XLWorkbook();

            var sheet = workbook.AddWorksheet("Rentals");

            var headerCells = new string[] { "Subscriber ID" , "Subscriber Name" , "Subscriber Phone" ,"Author Name", "Book Title" ,
                               "Rental Date", "End Date" , "Return Date" , "Extended On" };

            sheet.AddHeader(headerCells);

Bookify.Web/Views/Reports/Clinics.cshtml
@model ClinicReportViewModel;

@{
    ViewData["Title"] = "Clinics Report";
}

<div class="card mb-4">
    <dvi class="card-body">
        <form asp-controller="Reports" method="get" id="reportForm" class="js-exclude-validation">
            <input type="hidden" name="pageNumber" id="pageNumber" value="1" />
            <div class="row">
                <div class="col">
                    <div class="mb-5">
                        <div class="form-floating">
                            <select multiple class="form-select form-select-solid h-100 js-select" size="4" asp-for="SelectedAuthor" asp-items="@Model.Authors" data-placeholder="Selected Author">
                                <option>Selected Author</option>
                            </select>
                            <label asp-for="SelectedAuthor"></label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mb-5">
                        <div class="form-floating">
                            <select multiple class="form-select form-select-solid h-100 js-select" size="4" asp-for="SelectedCategories" asp-items="@Model.Categories" data-placeholder="select Categories">
                            </select>
                            <label asp-for="SelectedCategories"></label>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Show Report</button>
        </form>
    </dvi>
</div>

@if(Model.Books is not null)
{
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <span>Books</span>
            </div>
            @if (Model.Books.Any())
            {
                <div class="card-toolbar">
                    <a class="btn btn-sm btn-light-success" asp-action="ExportDatatoExcel"
                       asp-route-authors="@Context.Request.Query["SelectedAuthor"]" asp-route-categories="@Context.Request.Query["SelectedCategories"]">
                        <i class="bi bi-file-spreadsheet"></i>
                        Export to Excel
                    </a>
                    <a class="btn btn-sm btn-light-danger" asp-action="ExportDatatoPDF"
                       asp-route-authors="@Context.Request.Query["SelectedAuthor"]" asp-route-categories="@Context.Request.Query["SelectedCategories"]">
                        <i class="bi bi-file-earmark-pdf"></i>
                        Export to Pdf
                    </a>
                </div>
            }
        </div>
        <div class="card-body">
            @if(Model.Books.TotalPages > 1)
            {
                <partial name="_PaginationView" model="new PaginationViewModel { PageNumber = Model.Books.PageNumber, TotalPages = Model.Books.TotalPages}" />
            }
            @if (Model.Books.Any())
            {
                <div class="table-responsive">
                    <table class="table table-row-dashed table-row-gray-300 align-middle gy-4">
                        <thead>
                            <tr class="fw-bold fs-6 text-gray-800">
                                <th>Title</th>
                                <th>Author</th>
                                <th>Categories</th>
                                <th>Publisher</th>
                                <th>Publishing Date</th>
                                <th>Hall</th>
                                <th>Rental</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var book in Model.Books)
                            {
                                <tr>
                                    <td>@book.Title</td>
                                    <td>@book.Author!.Name</td>
                                    <td>@(string.Join(", ",book.Categories.Select(c => c.Category!.Name)))</td>
                                    <td>@book.Publisher</td>
                                    <td>@book.PublishingDate.ToString("dd-MM-yyyy")</td>
                                    <td>@book.Hall</td>
                                    <td>@(book.IsAvailableForRent ? "yes" : "no")</td>
                                    <td>@(book.IsDeleted ? "deleted" : "available")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <h5>No books were found!</h5>
            }
        </div>
    </div>
}
@section Scripts{
    <script src="~/js/report.js"></script>
}

Bookify.Web/Views/Reports/Doctors.cshtml
@model DoctorReportViewModel;

@{
    ViewData["Title"] = "Doctors Report";
}

@if (Model.PageMode == 1)
{
    <div class="card mb-4">
        <div class="card-body">
            <form asp-action="Doctors" method="get" id="reportForm" class="js-exclude-validation">
                <input type="hidden" name="From" id="From" />
                <input type="hidden" name="To" id="To" />
                <div class="row">
                    <div class="col">
                        <div class="mb-5">
                            <div data-kt-daterangepicker="true" data-kt-daterangepicker-opens="left" class="btn btn-sm btn-light d-flex align-items-center px-4" data-kt-initialized="1">
                                <!--begin::Display range-->
                                <div id="DateRange"></div>
                                <!--end::Display range-->
                                <i class="ki-duotone ki-calendar-8 text-gray-500 lh-0 fs-2 ms-2 me-0"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span><span class="path5"></span><span class="path6"></span></i>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Show Report</button>
            </form>
        </div>
    </div>
}


@if (Model.Rentals is not null)
{
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <span>Books</span>
            </div>
            @if (Model.Rentals.Any())
            {
                @if (Model.PageMode == 1)
                {
                    <div class="card-toolbar">
                        <a class="btn btn-sm btn-light-success" asp-action="ExportDoctortoExcel"
                           asp-route-from="@Context.Request.Query["From"]" asp-route-to="@Context.Request.Query["To"]">
                            <i class="bi bi-file-spreadsheet"></i>
                            Export to Excel
                        </a>
                        <a class="btn btn-sm btn-light-danger" asp-action="ExportDoctortoPDF"
                           asp-route-from="@Context.Request.Query["From"]" asp-route-to="@Context.Request.Query["To"]">
                            <i class="bi bi-file-earmark-pdf"></i>
                            Export to Pdf
                        </a>
                    </div>
                }
                else
                {
                    <div class="card-toolbar">
                        <a class="btn btn-sm btn-light-success" asp-action="ExportDelayedPatientToExcel">
                            <i class="bi bi-file-spreadsheet"></i>
                            Export to Excel
                        </a>
                        <a class="btn btn-sm btn-light-danger" asp-action="ExportDelayedPatientToPDF">
                            <i class="bi bi-file-earmark-pdf"></i>
                            Export to Pdf
                        </a>
                    </div>
                }

        }
        </div>
        <div class="card-body">
            @if (Model.Rentals.TotalPages > 1)
            {
                <partial name="_PaginationView" model="new PaginationViewModel { PageNumber = Model.Rentals.PageNumber, TotalPages = Model.Rentals.TotalPages}" />
            }
            @if (Model.Rentals.Any())
            {
                <div class="table-responsive">
                    <table class="table table-row-dashed table-row-gray-300 align-middle gy-4">
                        <thead>
                            <tr class="fw-bold fs-6 text-gray-800">
                                <th>Sub. ID</th>
                                <th>Sub. Name</th>
                                <th>Sub. Phone</th>
                                <th>Bk. Title</th>
                                <th>Bk. Author</th>
                                <th>Rental Date</th>
                                <th>End Date</th>
                                <th>Return Date</th>
                                <th>Extended On</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var rental in Model.Rentals)
                            {
                                <tr>
                                    <td>@rental.Rental!.Subscriper!.Id</td>
                                    <td>@rental.Rental!.Subscriper!.FirstName</td>
                                    <td>@rental.Rental!.Subscriper!.MobileNumber</td>
                                    <td>@rental.BookCopy!.Book!.Author!.Name</td>
                                    <td>@rental.BookCopy!.Book!.Title</td>
                                    <td>@rental.RentalDate.ToString("dd-MM-yyyy")</td>
                                    <td>@rental.EndDate.ToString("dd-MM-yyyy")</td>
                                    <td>@rental.ReturnDate?.ToString("dd-MM-yyyy")</td>
                                    <td>@rental.ExtendOn?.ToString("dd-MM-yyyy")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <h5>No rentals were found!</h5>
            }
        </div>
    </div>
}

@section Scripts {
    <script src="~/js/doctors.js"></script>
}

Bookify.Web/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "Reports";
}

<div class="d-flex flex-wrap flex-stack my-5">
    <!--begin::Heading-->
    <h3 class="fw-bold my-2">
        Reports
    </h3>
    <!--end::Heading-->
</div>
<div class="row g-6 g-xl-9 mb-6 mb-xl-9">
    <!--begin::Col-->
    <div class="col-md-6 col-lg-4 col-xl-3">
        <!--begin::Card-->
        <div class="card h-100 ">
            <!--begin::Card body-->
            <div class="card-body d-flex justify-content-center text-center flex-column p-8">
                <!--begin::Name-->
                <a asp-action="Clinics" class="text-gray-800 text-hover-primary d-flex flex-column">
                    <!--begin::Image-->
                    <div class="symbol symbol-60px mb-5">
                        <img src="~/assets/images/analysis.png" class="theme-light-show" alt="">
                        <img src="~/assets/images/analysis.png" class="theme-dark-show" alt="">
                    </div>
                    <!--end::Image-->
                </a>
                <!--end::Name-->
                <!--begin::Description-->
                <div class="fs-7 fw-semibold text-gray-500">
                    Clinics
                </div>
                <!--end::Description-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Card-->
    </div>
    <!--end::Col-->
    <!--begin::Col-->
    <div class="col-md-6 col-lg-4 col-xl-3">
        <!--begin::Card-->
        <div class="card h-100 ">
            <!--begin::Card body-->
            <div class="card-body d-flex justify-content-center text-center flex-column p-8">
                <!--begin::Name-->
                <a asp-action="Doctors" class="text-gray-800 text-hover-primary d-flex flex-column">
                    <!--begin::Image-->
                    <div class="symbol symbol-60px mb-5">
                        <img src="~/assets/images/analysis.png" class="theme-light-show" alt="">
                        <img src="~/assets/images/analysis.png" class="theme-dark-show" alt="">
                    </div>
                    <!--end::Image-->
                </a>
                <!--end::Name-->
                <!--begin::Description-->
                <div class="fs-7 fw-semibold text-gray-500">
                    Doctors
                </div>
                <!--end::Description-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Card-->
    </div>
    <!--end::Col-->
    <!--begin::Col-->
    <div class="col-md-6 col-lg-4 col-xl-3">
        <!--begin::Card-->
        <div class="card h-100 ">
            <!--begin::Card body-->
            <div class="card-body d-flex justify-content-center text-center flex-column p-8">
                <!--begin::Name-->
                <a asp-action="DelayedPatient" class="text-gray-800 text-hover-primary d-flex flex-column">
                    <!--begin::Image-->
                    <div class="symbol symbol-60px mb-5">
                        <img src="~/assets/images/analysis.png" class="theme-light-show" alt="">
                        <img src="~/assets/images/analysis.png" class="theme-dark-show" alt="">
                    </div>
                    <!--end::Image-->
                </a>
                <!--end::Name-->
                <!--begin::Description-->
                <div class="fs-7 fw-semibold text-gray-500">
                    Delayed Patients
                </div>
                <!--end::Description-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Card-->
    </div>
    <!--end::Col-->
</div>

Bookify.Web/Views/Reports/ReportDoctorPdf.cshtml
@model IEnumerable<RentalCopy>

@{
    Layout = "_PdfReportStyle";
}

<table>
    <thead>
        <tr>
            <th>Sub. ID</th>
            <th>Sub. Name</th>
            <th>Sub. Phone</th>
            <th>Bk. Title</th>
            <th>Bk. Author</th>
            <th>Rental Date</th>
            <th>End Date</th>
            <th>Return Date</th>
            <th>Extended On</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var rental in Model)
        {
            <tr>
                <td>@rental.Rental!.Subscriper!.Id</td>
                <td>@rental.Rental!.Subscriper!.FirstName</td>
                <td>@rental.Rental!.Subscriper!.MobileNumber</td>
                <td>@rental.BookCopy!.Book!.Author!.Name</td>
                <td>@rental.BookCopy!.Book!.Title</td>
                <td>@rental.RentalDate.ToString("dd-MM-yyyy")</td>
                <td>@rental.EndDate.ToString("dd-MM-yyyy")</td>
                <td>@rental.ReturnDate?.ToString("dd-MM-yyyy")</td>
                <td>@rental.ExtendOn?.ToString("dd-MM-yyyy")</td>
            </tr>
        }
    </tbody>
</table>

Bookify.Web/Views/Reports/ReportPdf.cshtml
@model IEnumerable<Book>

@{
    Layout = "_PdfReportStyle";
}

<table id="pdfTable">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Categories</th>
            <th>Publisher</th>
            <th>Publishing Date</th>
            <th>Hall</th>
            <th>Rental</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author!.Name</td>
                <td>@(string.Join(", ", book.Categories.Select(c => c.Category!.Name)))</td>
                <td>@book.Publisher</td>
                <td>@book.PublishingDate.ToString("dd-MM-yyyy")</td>
                <td>@book.Hall</td>
                <td>@(book.IsAvailableForRent ? "yes" : "no")</td>
                <td>@(book.IsDeleted ? "deleted" : "available")</td>
            </tr>
        }
    </tbody>
</table>