Bookify.Web/Controllers/AuthorsController.cs
using Bookify.Application.Common.Interfaces.Repository;
using Bookify.Web.Services;

namespace Bookify.Web.Controllers
{
    [Authorize(Roles = ApplicationRoles.Archive)]
    public class AuthorsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public AuthorsController(IMapper mapper,
             IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var authors = _unitOfWork.Authors.GetAll();

            var AuthorsViewModel = _mapper.Map<IEnumerable<AuthorViewModel>>(authors);

            return View(AuthorsViewModel);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Create()
        {
            return PartialView("_AuthorForm");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = _mapper.Map<Author>(model);
            author.CreatedById = User.GetUserId();

            var AuthorViewModal = _mapper.Map<AuthorViewModel>(_unitOfWork.Authors.Add(author));

            return PartialView("_AuthorRow", AuthorViewModal);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Edit(int Id)
        {
            var author = _unitOfWork.Authors.GetById(Id);

            if (author is null)
                return NotFound();

            var authorViewModal = _mapper.Map<AuthorFormViewModel>(author);

            return PartialView("_AuthorForm", authorViewModal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = _unitOfWork.Authors.GetById(model.Id);

            if (author is null)
                return NotFound();

            author.LastUpdatedOn = DateTime.Now;
            author.CreatedById = User.GetUserId();
            author.Name = model.Name;

            _unitOfWork.Authors.Update(author);
            _unitOfWork.SaveChanges();

            var AuthorViewModal = _mapper.Map<AuthorViewModel>(author);

            return PartialView("_AuthorRow", AuthorViewModal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggleStatus(int Id)
        {
            var author = _unitOfWork.Authors.GetById(Id); 

            if (author is null)
                return NotFound();

            author.IsDeleted = !author.IsDeleted;
            author.LastUpdatedOn = DateTime.Now;
            author.CreatedById = User.GetUserId();

            _unitOfWork.Authors.Update(author);
            _unitOfWork.SaveChanges();

            return Ok(author.LastUpdatedOn.ToString());
        }

        public IActionResult IsExist(AuthorFormViewModel model)
        {
            var author = _unitOfWork.Authors.Find(au => au.Name == model.Name);

            var isValid = author is null || author.Id.Equals(model.Id);

            return Json(isValid);
        }
    }
}

Bookify.Web/Controllers/BooksController.cs
using Bookify.Web.Cloudinary;
using Bookify.Web.Services;
using Microsoft.Extensions.Options;
using SixLabors.ImageSharp;
using System.Linq.Dynamic.Core;

namespace Bookify.Web.Controllers
{
    [Authorize(Roles = ApplicationRoles.Archive)]
    public class BooksController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly CloudinaryDotNet.Cloudinary _cloudinary;
        private readonly IImageService _imageService;

        private List<string> _allowedImageExtentions = new List<string> { ".jpg", ".jpeg", ".png" };
        private int _allowedImageSize = 2097152;

        public BooksController(ApplicationDbContext context, IMapper mapper,
            IWebHostEnvironment webHostEnvironment, IOptions<CloundinarySettings> cloudinary, IImageService imageService)
        {
            _context = context;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;

            Account acc = new()
            {
                Cloud = cloudinary.Value.Name,
                ApiKey = cloudinary.Value.APIKey,
                ApiSecret = cloudinary.Value.APISecret,
            };

            _cloudinary = new CloudinaryDotNet.Cloudinary(acc);
            _imageService = imageService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetBooks()
        {
            var skip = int.Parse(Request.Form["start"]);
            var pageSize = int.Parse(Request.Form["length"]);

            var searchParm = Request.Form["search[value]"];

            var orderIndex = Request.Form["order[0][column]"];

            var orderColumnName = Request.Form[$"columns[{orderIndex}][name]"];

            var sortDirection = Request.Form["order[0][dir]"];

            IQueryable<Book> books = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (!string.IsNullOrEmpty(searchParm))
                books = books.Where(b => b.Title.Contains(searchParm) || b.Author!.Name.Contains(searchParm));

            var recordsTotal = books.Count();

            books = books.OrderBy($"{orderColumnName} {sortDirection}");

            var data = books.Skip(skip).Take(pageSize).ToList();

            var dataMapped = _mapper.Map<IEnumerable<BookViewModel>>(data);

            return Ok(new { recoredsFiltered = recordsTotal, recordsTotal, data = dataMapped });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggleStatus(int Id)
        {
            var book = _context.Books.Find(Id);

            if (book is null)
                return NotFound();

            book.IsDeleted = !book.IsDeleted;
            book.LastUpdatedOn = DateTime.Now;
            book.LastUpdateById = User.GetUserId();

            _context.SaveChanges();

            return Ok();
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View("Form", PopulateBookModal());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Form", PopulateBookModal(model));

            var book = _mapper.Map<Book>(model);

            if (model.Image is not null)
            {
                var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image.FileName)}";
                var folderPath = $"/Images/Books/";

                var (isUploaded, errorMessage) = await _imageService.UploadAsync(model.Image, imageName, folderPath, hasThumbnail: true);

                if (!isUploaded)
                {
                    ModelState.AddModelError(nameof(model.Image), errorMessage!);
                    return View("Form", PopulateBookModal(model));
                }

                book.ImageUrl = $"{folderPath}{imageName}";
                book.ImageThumbUrl = $"{folderPath}thumb/{imageName}";



                //var imageExtension = Path.GetExtension(model.Image.FileName);
                //if(_allowedImageExtentions.Contains(imageExtension)
                //    && _allowedImageSize >= model.Image.Length)
                //{
                //    var imageName = $"{Guid.NewGuid()}{imageExtension}";

                //    var path = Path.Combine($"{_webHostEnvironment.WebRootPath}/Images/Books", imageName);
                //    var thumbPath = Path.Combine($"{_webHostEnvironment.WebRootPath}/Images/Books/thumb", imageName);

                //    using var stream = System.IO.File.Create(path);
                //    await model.Image.CopyToAsync(stream);
                //    stream.Dispose();

                //    book.ImageUrl = $"/Images/Books/{imageName}";
                //    book.ImageThumbUrl = $"/Images/Books/thumb/{imageName}";

                //    using var image = Image.Load(model.Image.OpenReadStream());
                //    var ratio = (float)image.Width / 200;
                //    var custHeight = image.Height / ratio;
                //    image.Mutate(i => i.Resize(width: 200, height: (int)custHeight));
                //    image.Save(thumbPath);
                //    image.Dispose();

                //using var stream = model.Image.OpenReadStream() ;
                //var imgParm = new ImageUploadParams
                //{
                //    File = new FileDescription(imageName,stream),
                //    UseFilename = true
                //};

                //var res = await _cloudinary.UploadAsync(imgParm);

                //book.ImageUrl = res.SecureUrl.ToString();
                //book.ImageThumbUrl = getThumbnailUrl(res.SecureUrl.ToString());
                //book.ImagePublicId = res.PublicId.ToString();
                // }
                //else
                //{
                //    ModelState.AddModelError(nameof(model.Image),
                //        "The image should be .jpg , .png And Max. length 2 MB");
                //    return View("Form",PopulateBookModal(model));
                //}
            }

            foreach (var category in model.SelectedCategories)
                book.Categories.Add(new BookCategory { CategoryId = category });

            book.CreatedById = User.GetUserId();

            _context.Books.Add(book);
            _context.SaveChanges();

            return RedirectToAction(nameof(Detials), new { Id = book.Id });
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var book = _context.Books.Include(b => b.Categories).SingleOrDefault(c => c.Id == Id);

            if (book is null)
                return NotFound();

            var model = _mapper.Map<BookFormViewModel>(book);
            var viewModel = PopulateBookModal(model);

            viewModel.SelectedCategories = book.Categories.Select(c => c.CategoryId).ToList();

            return View("Form", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
                return View("Form", PopulateBookModal(model));

            var book = _context.Books
                .Include(b => b.Categories)
                .Include(b => b.Copies)
                .SingleOrDefault(c => c.Id == model.Id);

            if (book is null)
                return NotFound();

            string ImagePublicId = null;

            if (model.Image is not null)
            {
                if (!string.IsNullOrEmpty(book.ImageUrl))
                    _imageService.Delete(book.ImageUrl, book.ImageThumbUrl);

                var imageName = $"{Guid.NewGuid()}{Path.GetExtension(model.Image.FileName)}";
                var folderPath = $"/Images/Books/";

                var (isUploaded, errorMessage) = await _imageService.UploadAsync(model.Image, imageName, folderPath, hasThumbnail: true);

                if (!isUploaded)
                {
                    ModelState.AddModelError(nameof(model.Image), errorMessage!);
                    return View("Form", PopulateBookModal(model));
                }

                model.ImageUrl = $"{folderPath}{imageName}";
                model.ImageThumbUrl = $"{folderPath}thumb/{imageName}";

                var imageExtension = Path.GetExtension(model.Image.FileName);

                //if (_allowedImageExtentions.Contains(imageExtension)
                //    && _allowedImageSize >= model.Image.Length)
                //{
                //              if (book.ImageUrl is not null)
                //              {
                //_imageService.Delete(book.ImageUrl, book.ImageThumbUrl);

                //var oldPath = $"{_webHostEnvironment.WebRootPath}{book.ImageUrl}";
                //                  var oldThumbPath = $"{_webHostEnvironment.WebRootPath}{book.ImageThumbUrl}";


                //                  if (System.IO.File.Exists(oldPath))
                //                      System.IO.File.Delete(oldPath);

                //                  if (System.IO.File.Exists(oldThumbPath))
                //                      System.IO.File.Delete(oldThumbPath);


                //await _cloudinary.DeleteResourcesAsync(book.ImagePublicId!);
                //}

                //var imageName = $"{Guid.NewGuid()}{imageExtension}";

                //using var stream = model.Image.OpenReadStream();
                //var imgParm = new ImageUploadParams
                //{
                //    File = new FileDescription(imageName, stream),
                //    UseFilename = true
                //};

                //var res = await _cloudinary.UploadAsync(imgParm);

Bookify.Web/Controllers/SearchController.cs
using HashidsNet;

namespace Bookify.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly IApplicationDbContext _context;
        private readonly IHashids _hashIds;
        private readonly IMapper _mapper;

        public SearchController(ApplicationDbContext context, IHashids hashids, IMapper mapper)
        {
            _context = context;
            _hashIds = hashids;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(string bKey)
        {
            var bookId = _hashIds.DecodeHex(bKey);
            var book = _context.Books
                .Include(b => b.Author)
                .Include(b => b.Copies)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category)
                .SingleOrDefault(b => b.Id == int.Parse(bookId));

            if (book is null)
                return NotFound();

            var viewModel = _mapper.Map<BookViewModel>(book);

            return View(viewModel);
        }

        public IActionResult Find(string query)
        {
            var books = _context.Books
                .Include(b => b.Author)
                .Where(b => !b.IsDeleted && (b.Title.Contains(query) || b.Author!.Name.Contains(query)))
                .Select(b => new { b.Title, author = b.Author!.Name, key = _hashIds.EncodeHex(b.Id.ToString()) })
                .ToList();

            return Ok(books);
        }
    }
}

Bookify.Web/Views/Shared/_Aside.cshtml
<!--begin::Aside-->
<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
	<!--begin::Aside menu-->
	<div class="aside-menu flex-column-fluid px-4">
		<!--begin::Aside Menu-->
		<div class="hover-scroll-overlay-y my-5 pe-4 me-n4" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="{default: '#kt_aside_footer', lg: '#kt_header, #kt_aside_footer'}" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="{default: '5px', lg: '75px'}">
			<!--begin::Menu-->
			<div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6" id="#kt_aside_menu" data-kt-menu="true">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" asp-controller="DashBoard" asp-action="Index" active-when="DashBoard">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path opacity="0.3" d="M10.9607 12.9128H18.8607C19.4607 12.9128 19.9607 13.4128 19.8607 14.0128C19.2607 19.0128 14.4607 22.7128 9.26068 21.7128C5.66068 21.0128 2.86071 18.2128 2.16071 14.6128C1.16071 9.31284 4.96069 4.61281 9.86069 4.01281C10.4607 3.91281 10.9607 4.41281 10.9607 5.01281V12.9128Z" fill="currentColor" />
									<path d="M12.9607 10.9128V3.01281C12.9607 2.41281 13.4607 1.91281 14.0607 2.01281C16.0607 2.21281 17.8607 3.11284 19.2607 4.61284C20.6607 6.01284 21.5607 7.91285 21.8607 9.81285C21.9607 10.4129 21.4607 10.9128 20.8607 10.9128H12.9607Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Dash Board</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" asp-controller="Search" asp-action="Index" active-when="Search">
						<span class="menu-icon">
							<!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor" />
									<path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor" />
								</svg>
							</span>
							<!--end::Svg Icon-->
						</span>
						<span class="menu-title">Search</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				@if (User.IsInRole(ApplicationRoles.Archive))
				{
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Categories" asp-action="Index" active-when="Categories">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path opacity="0.3" d="M21.25 18.525L13.05 21.825C12.35 22.125 11.65 22.125 10.95 21.825L2.75 18.525C1.75 18.125 1.75 16.725 2.75 16.325L4.04999 15.825L10.25 18.325C10.85 18.525 11.45 18.625 12.05 18.625C12.65 18.625 13.25 18.525 13.85 18.325L20.05 15.825L21.35 16.325C22.35 16.725 22.35 18.125 21.25 18.525ZM13.05 16.425L21.25 13.125C22.25 12.725 22.25 11.325 21.25 10.925L13.05 7.62502C12.35 7.32502 11.65 7.32502 10.95 7.62502L2.75 10.925C1.75 11.325 1.75 12.725 2.75 13.125L10.95 16.425C11.65 16.725 12.45 16.725 13.05 16.425Z" fill="currentColor" />
									<path d="M11.05 11.025L2.84998 7.725C1.84998 7.325 1.84998 5.925 2.84998 5.525L11.05 2.225C11.75 1.925 12.45 1.925 13.15 2.225L21.35 5.525C22.35 5.925 22.35 7.325 21.35 7.725L13.05 11.025C12.45 11.325 11.65 11.325 11.05 11.025Z" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Categories</span>
						</a>
						<!--end:Menu link-->
					</div>
					<!--end:Menu item-->
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Authors" asp-action="Index" active-when="Authors">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="currentColor" />
									<rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="currentColor" />
									<path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="currentColor" />
									<rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Authors</span>
						</a>
						<!--end:Menu link-->
					</div>
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Books" asp-action="Index" active-when="Books">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="currentColor" />
									<rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="currentColor" />
									<path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="currentColor" />
									<rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Books</span>
						</a>
						<!--end:Menu link-->
					</div>
				}
				@if (User.IsInRole(ApplicationRoles.Admin))
				{
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Users" asp-action="Index" active-when="Users">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="currentColor" />
									<rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="currentColor" />
									<path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="currentColor" />
									<rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Users</span>
						</a>
						<!--end:Menu link-->
					</div>
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Reports" asp-action="Index" active-when="Reports">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect x="8" y="9" width="3" height="10" rx="1.5" fill="currentColor" />
									<rect opacity="0.5" x="13" y="5" width="3" height="14" rx="1.5" fill="currentColor" />
									<rect x="18" y="11" width="3" height="8" rx="1.5" fill="currentColor" />
									<rect x="3" y="13" width="3" height="6" rx="1.5" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Reports</span>
						</a>
						<!--end:Menu link-->
					</div>
				}
				@if (User.IsInRole(ApplicationRoles.Reception))
				{
					<div class="menu-item">
						<!--begin:Menu link-->
						<a class="menu-link" asp-controller="Subscribers" asp-action="Index" active-when="Subscribers">
							<span class="svg-icon svg-icon-2">
								<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="currentColor" />
									<rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="currentColor" />
									<path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="currentColor" />
									<rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="currentColor" />
								</svg>
							</span>
							<span class="menu-title ms-3">Subscribers</span>
						</a>
						<!--end:Menu link-->
					</div>
				}
			</div>
			<!--end::Menu-->
		</div>
	</div>
	<!--end::Aside menu-->
</div>
<!--end::Aside-->

Bookify.Web/Views/Shared/_Modal.cshtml
<div class="modal" id="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabl"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalBody">
               
            </div>
        </div>
    </div>
</div>

Bookify.Web/Views/Shared/_ModalFooter.cshtml
<div class="modal-footer px-0">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary js-submit-btn">
        <span class="indicator-label">
            <i class="bi bi-check2"></i>
            Save
        </span>
        <span class="indicator-progress">
            Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
        </span>
    </button>
</div>