Bookify.Web/Controllers/RentalController.cs
using Microsoft.AspNetCore.DataProtection;

namespace Bookify.Web.Controllers
{
    public class RentalController : Controller
    {
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;
        private readonly IDataProtector _dataProtector;

        public RentalController(ApplicationDbContext context, IMapper mapper, IDataProtectionProvider dataProtectionProvider)
        {
            _context = context;
            _mapper = mapper;
            _dataProtector = dataProtectionProvider.CreateProtector("ProtectValue");
        }

        [HttpGet]
        public IActionResult Create(string sKey)
        {
            var subscriber = _context.Subscripers
                .Include(s => s.Subscriptions)
                .Include(s => s.Rentals)
                .ThenInclude(r => r.RentalCopies)
                .FirstOrDefault(s => s.Id == int.Parse(_dataProtector.Unprotect(sKey)));

            if (subscriber is null)
                return NotFound();

            var (errorMsg, maxAllowed) = SubscribtionValidation(subscriber);

            if (!string.IsNullOrEmpty(errorMsg))
                return View("NotAllowedRental", errorMsg);

            var viewModel = new RentalFormViewModel()
            {
                SubscriberKey = sKey,
                MaxAllowed = maxAllowed
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RentalFormViewModel model)
        {

            if (!ModelState.IsValid)
                return View(model);

            var subscriberId = int.Parse(_dataProtector.Unprotect(model.SubscriberKey));

            var subscriber = _context.Subscripers
                .Include(s => s.Subscriptions)
                .Include(s => s.Rentals)
                .ThenInclude(r => r.RentalCopies)
                .FirstOrDefault(s => s.Id == subscriberId);

            if (subscriber is null)
                return NotFound();

            var (copies, errorMsg) = CheckRental(model);

            if (copies is null)
                return View("NotAllowedRental", errorMsg);


            Rental rental = new()
            {
                RentalCopies = copies,
                CreatedById = User.GetUserId()
            };

            subscriber.Rentals.Add(rental);
            _context.SaveChanges();

            return RedirectToAction(nameof(Details), new { id = rental.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GetCopyDetials(SearchViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var copy = _context.BookCopies.Include(c => c.Book)
                .SingleOrDefault(c => c.SerialNumber.ToString() == model.Value && !c.IsDeleted && !c.Book!.IsDeleted);

            if (copy is null)
                return NotFound(Errors.InvalidSerialNumber);

            if (!copy.IsAvailableForRental || !copy.Book!.IsAvailableForRent)
                return NotFound(Errors.NotAvliableForRental);

            //var Rentaled = _context.RentalCopies.Where(c => c.BookCopyId == copy.BookId && !c.ReturnDate.HasValue);

            var copyIsRentaled = _context.RentalCopies.Any(c => c.BookCopyId == copy.Id && !c.ReturnDate.HasValue);

            if (copyIsRentaled)
                return BadRequest(Errors.CopyIsRentaled);

            var viewModel = _mapper.Map<BookCopyViewModel>(copy);

            return PartialView("_CopyDetials", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CancelRental(int id)
        {
            var rental = _context.Rentals.Find(id);

            if (rental is null || rental.CreatedOn.Date != DateTime.Today)
                return NotFound();

            rental.IsDeleted = true;
            rental.LastUpdatedOn = DateTime.Now;
            rental.LastUpdateById = User.GetUserId();

            _context.SaveChanges();

            return Ok();
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            var rental = _context.Rentals
                .Include(r => r.RentalCopies)
                .ThenInclude(r => r.BookCopy)
                .ThenInclude(b => b!.Book)
                .FirstOrDefault(r => r.Id == Id);

            if (rental is null)
                return NotFound();

            var viewModel = _mapper.Map<RentalViewModel>(rental);

            return View("Details", viewModel);

        }


        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var rental = _context.Rentals
                .Include(r => r.Subscriper)
                .Include(r => r.RentalCopies)
                .ThenInclude(c => c.BookCopy)
                .SingleOrDefault(r => r.Id == Id);

            if (rental is null || rental.CreatedOn.Date != DateTime.Today)
                return NotFound();

            var subscriber = _context.Subscripers
                .Include(s => s.Subscriptions)
                .Include(s => s.Rentals)
                .ThenInclude(r => r.RentalCopies)
                .FirstOrDefault(r => r.Id == rental.Subscriper!.Id);


            var selectedBookIds = rental.RentalCopies.Select(s => s.BookCopyId).ToList();

            var selectedBooks = _context.BookCopies
                .Where(b => selectedBookIds.Contains(b.Id))
                .Include(b => b.Book)
                .ToList();

            var (errorMsg, maxAllowed) = SubscribtionValidation(subscriber!, rental.Id);

            var viewModel = new RentalFormViewModel()
            {
                SubscriberKey = _dataProtector.Protect(subscriber!.Id.ToString()),
                MaxAllowed = maxAllowed,
                CurrentCopies = _mapper.Map<IEnumerable<BookCopyViewModel>>(selectedBooks)
            };

            return View(nameof(Create), viewModel);
        }


        [HttpGet]
        public IActionResult Return(int id)
        {
            var rental = _context.Rentals
                .Include(r => r.Subscriper)
                .ThenInclude(s => s!.Subscriptions)
                .Include(r => r.RentalCopies.Where(c => !c.ReturnDate.HasValue))
                .ThenInclude(c => c.BookCopy)
                .ThenInclude(c => c!.Book)
                .SingleOrDefault(r => r.Id == id);

            if (rental is null || rental.CreatedOn.Date == DateTime.Today)
                return NotFound();

            var viewModel = new RentalReturnFormViewModel
            {
                Id = id,

                Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies),
                SelectedCopies = rental.RentalCopies.Select(c => new ReturnCopyOption { Id = c.BookCopyId, IsReturned = c.ExtendOn.HasValue ? false : null }).ToList(),
                AllowExtend = !rental.Subscriper!.IsBlackListed
                && rental.Subscriper.Subscriptions.Last().EndDate >= rental.StartDate.AddDays((int)ApplicationEnums.MaxRentalDuration)
                && rental.StartDate.AddDays((int)ApplicationEnums.RentalDuration) >= DateTime.Today
            };

            //viewModel.TotalDelayInDays = viewModel.Copies.Sum(c => c.DelayInDays);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Return(RentalReturnFormViewModel model)
        {
            var rental = _context.Rentals
                .Include(r => r.Subscriper)
                .ThenInclude(s => s!.Subscriptions)
                .Include(r => r.RentalCopies)
                .ThenInclude(c => c.BookCopy)
                .ThenInclude(c => c!.Book)
                .SingleOrDefault(r => r.Id == model.Id);

            if (rental is null || rental.CreatedOn.Date == DateTime.Today)
                return NotFound();

            if (!ModelState.IsValid)
            {
                model.Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies);
                return View(model);
            }

            var subscriber = rental.Subscriper;

            if (model.SelectedCopies.Any(c => c.IsReturned.HasValue && !c.IsReturned.Value))
            {
                model.Copies = _mapper.Map<IList<RentalCopyViewModel>>(rental.RentalCopies);

                if (subscriber!.IsBlackListed)
                    ModelState.AddModelError("", Errors.BlackListedSubscriber);

                if (subscriber!.Subscriptions.Last().EndDate < rental.StartDate.AddDays((int)ApplicationEnums.MaxRentalDuration))
                    ModelState.AddModelError("", Errors.SubsucriberNotAllowedToExtend);

                if (rental.StartDate.AddDays((int)ApplicationEnums.MaxRentalDuration) < DateTime.Today)
                    ModelState.AddModelError("", Errors.SubsucriberNotAllowedToExtend);

                if (ModelState.ErrorCount != 0)
                    return View(model);
            }

            var isUpdated = false;

            foreach (var copy in model.SelectedCopies)
            {
                if (!copy.IsReturned.HasValue) continue;

                var currentCopy = rental.RentalCopies.SingleOrDefault(r => r.BookCopyId == copy.Id);

                if (currentCopy is null) continue;

                if (copy.IsReturned.HasValue && copy.IsReturned.Value)
                {
                    if (currentCopy.ReturnDate.HasValue) continue;

                    isUpdated = true;
                    currentCopy.ReturnDate = DateTime.Now;
                }

                if (copy.IsReturned.HasValue && !copy.IsReturned.Value)
                {
                    if (currentCopy.ExtendOn.HasValue) continue;

                    isUpdated = true;
                    currentCopy.ExtendOn = DateTime.Now;
                    currentCopy.EndDate = currentCopy.RentalDate.AddDays((int)ApplicationEnums.MaxRentalDuration);
                }
            }

            if (isUpdated)

Bookify.Web/Views/Rental/Create.cshtml
@model RentalFormViewModel

@{
    var title = Model.CurrentCopies.Any() ? "Edit" : "Add";
    ViewData["Title"] = title +" Rental";
}

<div class="card mb-7">
    <div class="card-header">
        <h3 class="card-title">@title Rental</h3>
    </div>
    <div class="card-body">
        <partial name="_SearchRental" model="new SearchViewModel()" />
    </div>
    <div class="card mb-5 mb-xl-8">
        <!--begin::Header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bold text-gray-900">Books</span>
                <span class="text-muted mt-1 fw-semibold fs-7">You can add Up to @Model.MaxAllowed book(s)</span>
            </h3>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body pt-5">
            <form asp-controller="Rental" id="CopiesForm">
                <input type="hidden" asp-for="SubscriberKey" />
                @foreach (var copy in Model.CurrentCopies)
                {
                    <partial name="_CopyDetials" model="copy" />
                }
                <button type="submit" class="btn btn-primary js-submit-btn d-none">
                    <span class="indicator-label">
                        <i class="bi bi-check2"></i>
                        Save
                    </span>
                    <span class="indicator-progress">
                        Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                    </span>
                </button>
            </form>
        </div>
        <!--end::Body-->
    </div>
</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script>
        var maxSelectedCopies = @Model.MaxAllowed;
    </script>
    <script src="~/js/rental-form.js"></script>
}

Bookify.Web/Views/Rental/Details.cshtml
@model RentalViewModel

@{
    ViewData["Title"] = "Rental Details";
}

<div class="alert bg-light-primary border border-primary border-3 border-dashed d-flex justify-content-between w-100 p-5 mb-10">
    <div class="d-flex align-items-center">
        <div class="symbol symbol-40px me-4">
            <div class="symbol-label fs-2 fw-semibold text-success">
                <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                <span class="svg-icon svg-icon-2 svg-icon-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path opacity="0.3" d="M20 15H4C2.9 15 2 14.1 2 13V7C2 6.4 2.4 6 3 6H21C21.6 6 22 6.4 22 7V13C22 14.1 21.1 15 20 15ZM13 12H11C10.5 12 10 12.4 10 13V16C10 16.5 10.4 17 11 17H13C13.6 17 14 16.6 14 16V13C14 12.4 13.6 12 13 12Z" fill="currentColor" />
                        <path d="M14 6V5H10V6H8V5C8 3.9 8.9 3 10 3H14C15.1 3 16 3.9 16 5V6H14ZM20 15H14V16C14 16.6 13.5 17 13 17H11C10.5 17 10 16.6 10 16V15H4C3.6 15 3.3 14.9 3 14.7V18C3 19.1 3.9 20 5 20H19C20.1 20 21 19.1 21 18V14.7C20.7 14.9 20.4 15 20 15Z" fill="currentColor" />
                    </svg>
                </span>
                <!--end::Svg Icon-->
            </div>
        </div>
        <!--begin::Content-->
        <div class="d-flex flex-column pe-0 pe-sm-10">
            <h5 class="mb-1">Rental Details</h5>
        </div>
        <!--end::Content-->
    </div>
    @if (Model.CreatedOn.Date == DateTime.Today)
    {
        <div>
            <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@Model.Id">
                <i class="bi bi-plus-square-dotted"></i>
                Edit
            </a>
        </div>
    }
    else if(Model.RentalCopies.Any(c => !c.ReturnDate.HasValue))
    {
        <div>
            <a class="btn btn-sm btn-primary" asp-action="Return" asp-route-id="@Model.Id">
                <i class="bi bi-plus-square-dotted"></i>
                Return
            </a>
        </div>
    }
</div>

<div class="card pt-4 mb-6 mb-xl-9">
    <!--begin::Card header-->
    <div class="card-header border-0 pt-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bold fs-3 mb-1">Books</span>
        </h3>
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body pt-0 pb-5">
        <div class="alert bg-light-info border border-info border-3 border-dashed d-flex flex-column flex-sm-row w-100 p-5 mt-10" style="display: none !important" id="Alert">
            <!--begin::Icon-->
            <!--begin::Svg Icon | path: icons/duotune/general/gen007.svg-->
            <span class="svg-icon svg-icon-2hx svg-icon-info me-4 mb-5 mb-sm-0">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path opacity="0.3" d="M12 22C13.6569 22 15 20.6569 15 19C15 17.3431 13.6569 16 12 16C10.3431 16 9 17.3431 9 19C9 20.6569 10.3431 22 12 22Z" fill="currentColor"></path>
                    <path d="M19 15V18C19 18.6 18.6 19 18 19H6C5.4 19 5 18.6 5 18V15C6.1 15 7 14.1 7 13V10C7 7.6 8.7 5.6 11 5.1V3C11 2.4 11.4 2 12 2C12.6 2 13 2.4 13 3V5.1C15.3 5.6 17 7.6 17 10V13C17 14.1 17.9 15 19 15ZM11 10C11 9.4 11.4 9 12 9C12.6 9 13 8.6 13 8C13 7.4 12.6 7 12 7C10.3 7 9 8.3 9 10C9 10.6 9.4 11 10 11C10.6 11 11 10.6 11 10Z" fill="currentColor"></path>
                </svg>
            </span>
            <!--end::Svg Icon-->
            <!--end::Icon-->
            <!--begin::Content-->
            <div class="d-flex flex-column pe-0 pe-sm-10 justify-content-center">
                <h5 class="mb-0">This subscriber has no rentals yet.</h5>
            </div>
            <!--end::Content-->
        </div>

        <div class="table-responsive " id="Table">
            <!--begin::Table-->
            <table class="table align-middle gs-0 gy-4">
                <!--begin::Table head-->
                <thead>
                    <tr class="fw-bold text-muted bg-light">
                        <th class="ps-12 min-w-125px rounded-start">Book(s)</th>
                        <th class="min-w-125px">Start Date</th>
                        <th class="min-w-125px">End Date</th>
                        <th class="min-w-150px">Total Delay (Days)</th>
                        <th class="min-w-150px">Extend Date</th>
                        <th class="min-w-150px rounded text-end pe-10">Return Date</th>
                    </tr>
                </thead>
                <!--end::Table head-->
                <!--begin::Table body-->
                <tbody>
                    @foreach (var copy in Model.RentalCopies)
                    {
                        <tr>
                            <td>
                                <div class="d-flex align-items-center ps-3">
                                    <!--begin::Symbol-->
                                    <div class="symbol symbol-40px me-5">
                                        <img src="@copy.BookCopy?.BookThumbnailUrl" class="h-50 align-self-center" alt="@copy.BookCopy?.BookTitle">
                                    </div>
                                    <!--end::Symbol-->
                                    <div class="d-flex align-items-center flex-row-fluid flex-wrap">
                                        <!--begin:Author-->
                                        <div class="flex-grow-1 me-2">
                                            <h4 class="text-gray-800 text-hover-primary fs-6 fw-bold">@copy.BookCopy?.BookTitle</h4>
                                            <span class="text-muted fw-semibold d-block fs-7">Edition# @copy.BookCopy?.EditionNumber</span>
                                        </div>
                                        <!--end:Author-->
                                    </div>
                                    <!--end::Section-->
                                </div>
                            </td>
                            <td>
                                @copy.RentalDate.ToString("d MMM, yyyy")
                            </td>
                            <td>
                                @copy.EndDate.ToString("d MMM, yyyy")
                            </td>
                            <td class="@(copy.DelayInDays > 0 ? "text-danger" : string.Empty)">
                                @copy.DelayInDays Day(s)
                            </td>
                            <td class="pe-4">
                                @copy.ExtendOn?.ToString("d MMM, yyyy")
                            </td>
                            <td class="text-end pe-10">
                                @copy.ReturnDate?.ToString("d MMM, yyyy")
                            </td>
                        </tr>
                    }
                </tbody>
                <!--end::Table body-->
            </table>
            <!--end::Table-->
        </div>
    </div>
    <!--end::Card body-->
</div>

Bookify.Web/Views/Rental/NotAllowedRental.cshtml
@model string

@{
    ViewData["Title"] = "Not Allowed Rental";
}

<div class="d-flex flex-column text-center align-items-center">
    <img src="~/assets/images/stopimg.jpg" class="mw-200px" />
    <h1 class=" badge-danger text-white w-50 rounded p-4">@Model</h1>
</div>

Bookify.Web/Views/Rental/Return.cshtml
@model RentalReturnFormViewModel;

@{
    ViewData["Title"] = "Return Copy";
}

@if (Model.Copies.All(c => c.ReturnDate.HasValue))
{
    <div class="alert bg-light-info border border-info border-3 border-dashed d-flex flex-column flex-sm-row w-100 p-5 mt-10" id="Alert">
        <!--begin::Icon-->
        <!--begin::Svg Icon | path: icons/duotune/general/gen007.svg-->
        <span class="svg-icon svg-icon-2hx svg-icon-info me-4 mb-5 mb-sm-0">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path opacity="0.3" d="M12 22C13.6569 22 15 20.6569 15 19C15 17.3431 13.6569 16 12 16C10.3431 16 9 17.3431 9 19C9 20.6569 10.3431 22 12 22Z" fill="currentColor"></path>
                <path d="M19 15V18C19 18.6 18.6 19 18 19H6C5.4 19 5 18.6 5 18V15C6.1 15 7 14.1 7 13V10C7 7.6 8.7 5.6 11 5.1V3C11 2.4 11.4 2 12 2C12.6 2 13 2.4 13 3V5.1C15.3 5.6 17 7.6 17 10V13C17 14.1 17.9 15 19 15ZM11 10C11 9.4 11.4 9 12 9C12.6 9 13 8.6 13 8C13 7.4 12.6 7 12 7C10.3 7 9 8.3 9 10C9 10.6 9.4 11 10 11C10.6 11 11 10.6 11 10Z" fill="currentColor"></path>
            </svg>
        </span>
        <!--end::Svg Icon-->
        <!--end::Icon-->
        <!--begin::Content-->
        <div class="d-flex flex-column pe-0 pe-sm-10 justify-content-center">
            <h5 class="mb-0">All Copies have been returned.</h5>
        </div>
        <!--end::Content-->
    </div>
}
else
{
    <form asp-controller="Rental">
        <div class="card pt-4 mb-6 mb-xl-9">
            <!--begin::Card header-->
            <div class="card-header border-0 pt-5">
                <h3 class="card-title align-items-start flex-column">
                    <span class="card-label fw-bold fs-3 mb-1">Books</span>
                </h3>
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-0 pb-5">
                <div class="table-responsive " id="Table">
                    <!--begin::Table-->
                    <table class="table align-middle gs-0 gy-4">
                        <!--begin::Table head-->
                        <thead>
                            <tr class="fw-bold text-muted bg-light">
                                <th class="ps-12 min-w-125px rounded-start">Book(s)</th>
                                <th class="min-w-125px">Start Date</th>
                                <th class="min-w-125px">End Date</th>
                                <th class="min-w-150px">Total Delay (Days)</th>
                                <th class="min-w-150px">Extend Date</th>
                                <th class="min-w-150px">Return Date</th>
                                <th class="min-w-100px">Return</th>
                                <th class="min-w-100px rounded">Extend</th>
                            </tr>
                        </thead>
                        <!--end::Table head-->
                        <!--begin::Table body-->
                        <tbody>
                            @for (var i = 0; i < Model.Copies.Count; i++)
                            {
                                var copy = Model.Copies[i];
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center ps-3">
                                            <!--begin::Symbol-->
                                            <div class="symbol symbol-40px me-5">
                                                <img src="@copy.BookCopy?.BookThumbnailUrl" class="h-50 align-self-center" alt="@copy.BookCopy?.BookTitle">
                                            </div>
                                            <!--end::Symbol-->
                                            <div class="d-flex align-items-center flex-row-fluid flex-wrap">
                                                <!--begin:Author-->
                                                <div class="flex-grow-1 me-2">
                                                    <h4 class="text-gray-800 text-hover-primary fs-6 fw-bold">@copy.BookCopy?.BookTitle</h4>
                                                    <span class="text-muted fw-semibold d-block fs-7">Edition# @copy.BookCopy?.EditionNumber</span>
                                                </div>
                                                <!--end:Author-->
                                            </div>
                                            <!--end::Section-->
                                        </div>
                                    </td>
                                    <td>
                                        @copy.RentalDate.ToString("d MMM, yyyy")
                                    </td>
                                    <td>
                                        @copy.EndDate.ToString("d MMM, yyyy")
                                    </td>
                                    <td class="@(copy.DelayInDays > 0 ? "text-danger" : string.Empty)">
                                        @copy.DelayInDays Day(s)
                                    </td>
                                    <td class="pe-4">
                                        @copy.ExtendOn?.ToString("d MMM, yyyy")
                                    </td>
                                    <td class="">
                                        @copy.ReturnDate?.ToString("d MMM, yyyy")
                                    </td>
                                    <td>
                                        <div class="form-check form-check-custom form-check-success form-check-solid">
                                            <input type="hidden" asp-for="@Model.SelectedCopies[i].Id" id="@($"{Model.SelectedCopies[i].Id}_true_id")" />
                                            <input class="form-check-input" type="radio" asp-for="@Model.SelectedCopies[i].IsReturned" value="true" id="@($"{Model.SelectedCopies[i].Id}_true")" />
                                        </div>
                                    </td>
                                    <td class="text-end pe-10">
                                        <div class="form-check form-check-custom form-check-custom form-check-solid">
                                            <input type="hidden" asp-for="@Model.SelectedCopies[i].Id" id="@($"{Model.SelectedCopies[i].Id}_false_id")" />
                                            <input class="form-check-input" type="radio" asp-for="@Model.SelectedCopies[i].IsReturned" value="false" id="@($"{Model.SelectedCopies[i].Id}_false")" disabled="@(Model.AllowExtend ? null : "disabled")" />
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <!--end::Table body-->
                    </table>
                    <!--end::Table-->
                    @if(Model.TotalDelayInDays > 0)
                    {
                        <div class="ps-4">
                            <div class="form-check form-check-custom form-check-custom form-check-solid">
                                <input type="hidden" asp-for="TotalDelayInDays" />
                                <input class="form-check-input" type="checkbox" asp-for="IsPenalitesPaied" />
                                <label class="form-check-label" asp-for="IsPenalitesPaied"></label>
                            </div>
                        </div>
                    }
                    
                    <div asp-validation-summary="All" class="text-danger"></div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary js-submit-btn">
                        <span class="indicator-label">
                            <i class="bi bi-check2"></i>
                            Save
                        </span>
                        <span class="indicator-progress">
                            Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                        </span>
                    </button>
                </div>
            </div>
            <!--end::Card body-->
        </div>
    </form>
}


@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Bookify.Web/Views/Rental/_CopyDetials.cshtml
@model BookCopyViewModel

<div class="js-row-copy">
    <div class="d-flex flex-stack">
        <input type="hidden" value="@Model.SerialNumber" class="js-copy" data-book-id="@Model.BookId" />
        <!--begin::Symbol-->
        <div class="symbol symbol-40px me-5">
            <img src="@Model.BookThumbnailUrl" class="h-50 align-self-center" alt="@Model.BookTitle">
        </div>
        <!--end::Symbol-->
        <!--begin::Section-->
        <div class="d-flex align-items-center flex-row-fluid flex-wrap">
            <!--begin:Author-->
            <div class="flex-grow-1 me-2">
                <h4 class="text-gray-800 text-hover-primary fs-6 fw-bold">@Model.BookTitle</h4>
                <span class="text-muted fw-semibold d-block fs-7">Editio# @Model.EditionNumber</span>
            </div>
            <!--end:Author-->
            <!--begin:Action-->
            <a href="javascript:;" class="btn btn-sm btn-danger fs-8 fw-bold js-remove-btn">Remove</a>
            <!--end:Action-->
        </div>
        <!--end::Section-->
    </div>
    <div class="separator separator-dashed my-4"></div>
</div>

Bookify.Web/Views/Rental/_SearchRental.cshtml
@model SearchViewModel

<form asp-action="GetCopyDetials"
    data-ajax-method="post"  
    data-ajax="true"
    data-ajax-success="OnAddCopySuccess"
      data-ajax-begin="DisableBtnWhenProcessing"
      data-ajax-failure="showErrorMessage"
      data-ajax-complete="OnModalComplete" id="SerchForm">
    <div class="d-flex align-items-center">
        <!--begin::Input group-->
        <div class="position-relative w-md-400px me-md-2">
            <i class="ki-duotone ki-magnifier fs-3 text-gray-500 position-absolute top-50 translate-middle ms-6"><span class="path1"></span><span class="path2"></span></i>
            <input type="text" class="form-control form-control-solid ps-10" asp-for="Value" placeholder="Search by serial number ... ">
        </div>
        <!--end::Input group-->
        <!--begin:Action-->
        <div class="d-flex align-items-center">
            <button type="submit" class="btn btn-primary me-5 js-search">Search</button>
        </div>
        <!--end:Action-->
    </div>
</form>